### ISSUE TITLE
Frontend To-do's (성준님)

### ISSUE THREAD

**Issue by jaenam615** [jaenam615/cosmetic_routine#34]
- [ ]  제품페이지에서 브랜드/용량 그리기 - brand_name / volume 

- [ ]  루틴 추가에 제품 : GET /api/item/search/:query 
	- [ ]  루틴 생성에서 제품 선택 시 칸은 item_name으로 채우고 전달하는 body 에는 item_key로 전달

- [ ]  Routine 상태 지우기

- [ ]  루틴상세에서 GET /api/item/key/:item_key 아이템 받아와서 그리기

- [ ]  리뷰 GET /api/item/:item_key/review GET /api/routine/:routine_key/review

- [ ]  Main page 에서 루틴 및 아이템 누를 때 해당 페이지로 연결 

- [ ]  제품 목록 검색/ 루틴 목록 검색 : 페이지 자체가 다시 그려지게 (필터를 선택한 것 마냥) >> :query

- [ ]  메인 페이지 검색: 일단 GET /api/routine/search/:query

- [ ]  mypage 주문내역 아래에 '배송지 관리'

- [ ]  title & logo 

- [ ] 공지사항

- [ ] item description textarea

**Comment by jaenam615** [comment]
- [ ] 루틴 전체 조회 페이지에서 이미지
- [ ] 리뷰 등록 디자인과 리뷰 조회 디자인

**Comment by jaenam615** [comment]
**마이페이지**
- [ ] 로그인 안되어 있을 시 (토큰 없을 시) 주문 내역 또는 배송지 관리 누르면 -> 로그인후 사용해주세요 라는 팝업에러 뜨기
- [ ] 로그아웃 버튼은 로그인 되어있을 때만 보이도록

**주문 내역**  
- [ ] itemOrder 받아와서 그리기 GET /api/order

**장바구니** 
- [ ] cart 받아와서 그리기 GET /api/cart (header에 토큰 필요) 
*****
[
    {
        "cart_key": 1,
        "user_key": 1,
        "item_key": 1,
        "quantity": 1,
        "item": {
            "item_key": 1,
            "item_name": "testItem1",
            "brand_name": "brand1",
            "volume": 10,
            "item_price": 1000,
            "description": "테스트 아이템입니다.",
            "category": "지성"
        }
    },
    {
        "cart_key": 2,
        "user_key": 1,
        "item_key": 2,
        "quantity": 1,
        "item": {
            "item_key": 2,
            "item_name": "testItem2",
            "brand_name": "brand2",
            "volume": 50,
            "item_price": 10000,
            "description": "테스트 아이템입니다.",
            "category": "건성"
        }
    }
]
*****
이렇게 받기 때문에 여기서 브랜드, 제품명, 용량 수량을 미리 그리고 아래 가격은 수량 * 가격 해서 그리면 됩니다. 
- [ ] 제품 상세 또는 루틴에서 [장바구니] 버튼 누르면 수량(quantity) 정하는 모달 팝업 -> 문구: 수량을 선택해주세요
해당 아이템을 장바구니에 넣기 POST /api/cart 
(header에 토큰 필요) (body는 item_key, quantity) 
- [ ] 장바구니 내에서 해당 제품의 수량 변경 가능

**Comment by jaenam615** [comment]
- [ ] 배송지 관리에서는 모든 배송지들을 띄우고, 맨 위쪽 어딘가에 '배송지 추가' 버튼을 만들어주세요. 
      - [ ] GET /api/user/:user_key/address 
      - [ ] POST /api/user/:user_key/address 이건 그냥 form으로 만들어주시면 됩니다. 
 - [ ] 배송지 관리에서 모든 배송지 띄운 상태에서, 어딘가에 '수정'버튼 만들어주시고, 수정 form으로 연결해주시되, 모든 값들이 미리 채워져있어야 합니다 (기존 배송지 정보). 그리고 거기서 수정 완료 버튼을 누르면 PUT /api/user/:user_key/address/:addr_key 로 보내면 됩니다. 
 - [ ] 비슷하게 '삭제'버튼도 만들어주시고 이건 그냥 누르면 [배송지를 삭제하시겠습니까?] 팝업 띄워주고 '예' 누르면 DELETE /api/user/:user_key/address/:addr_key 로 보내면 됩니다.

**Comment by jaenam615** [comment]
- [ ] 장바구니 금액 아래에 보여주기
![image](https://github.com/user-attachments/assets/8eefbec8-77d1-467c-8dd8-decdc12cb08a)

- [ ] 로그인 된 상태에서만 루틴 추가 + 버튼 누를 수 있도록 (버튼을 없애거나 누르면 '로그인해주세요' 라는 팝업 뜨도록) 

- [ ] 리뷰 작성 로그인 된 상태에서만 가능하도록

**Comment by CamelIsTheBestConvention** [comment]
- [ ] 장바구니 추가 버튼과 구매 버튼은 로그인 안 했을 때 로그인 해달라는 alert창과 함께 로그인 페이지로 이동
- [ ] 프로필 수정 구현
- [ ] 결제 모듈

**Comment by jaenam615** [comment]
- [ ] 결제 완료 result.data.status === "paid" 이면 -> 성공페이지로 넘어가되, 넘어가면서(?) API 요청 -> POST /api/order/itemorder로 

{
addr_key: 1
price total: 1000
items: [{
count : quantity(....)
purchase_price: 아이템 1개당 가격 
item_key: 아이템키
}, { }, { }]
}

- [ ] 결제 성공페이지는 result.data 에 있는 데이터 써서 그리기 (뭐 결제코드, 결제 금액 등)

- [ ] 실패도 뭐가 있을 터. 비슷하게 구현.

**Comment by jaenam615** [comment]
- [ ] 주소 API (선택사항)
- [ ] 장바구니 default가 체크되어있도록
- [ ] 돌아가서 단계 개수 수정 시 단계가 제대로 반영이 되지 아니함
- [ ] TOP10현재 별점정렬 -> 댓글 수 정렬 
- [ ] 판매자 대시보드 (판매자모드)

**Comment by CamelIsTheBestConvention** [comment]
ㄴㅁㅇ리ㅏㅁㄴㅇ런ㄻ아;ㅣㅓㄹㄴㅇㅁ'ㅣㅏ;ㅁㄹㄴㅇ

**Comment by CamelIsTheBestConvention** [comment]
루틴추가 버그 도저히 안고쳐져서 인나서 다시 구현하겠습니다;;;

**Comment by CamelIsTheBestConvention** [comment]
- [ ] 루틴 수정이나 삭제를 구현 안 한것 같아 추가

**Comment by CamelIsTheBestConvention** [comment]
- [ ] 전체 루틴 페이지 루틴 속성 타입 출력
- [ ] 상세 루틴 페이지 구조 변경 & 속성 타입과 태그 출력
- [ ] 루틴 수정
- [ ] 루틴 삭제
- [ ] 루틴 추가 페이지 초기화 안되는 버그 수정
- [ ] 루틴 필터, 제품 필터 초기화 버튼 추가
- [ ] 배송지 UI변경
- [ ] 배송지 추가 시 모든 input 작성해야 활성화되게 변경
- [ ] 루틴, 제품 호버 시 이펙트 추가

**Comment by CamelIsTheBestConvention** [comment]
- [ ] 결제 페이지 UI 구현
- [ ] 배송지 변경 수정 에러
- [ ] 마이페이지 사용되지 않는 기능 접근 못하게 막기

**Comment by CamelIsTheBestConvention** [comment]
- [x] 최종 결제 페이지 배송지 변경으로 팝업창이 열려있을 시 기존 페이지 막아두기

**Comment by moonmisae118** [comment]
24.12.08 issue
- [x] 결제 페이지 배송지 선택 오류(배송지 없으면 예외처리로 막아둠)
- [x] 결제 페이지 배송지 없을 때 결제 버튼 막기
- [x] 메인 페이지 검색 결과 선택 오류
- [x] 메인 페이지 루틴에 가장 많이 사용된 제품 브랜드 동적으로 변경
- [ ] 마이 페이지 주소지 한 개 남아있으면 삭제 불가 오류
- [ ] 검색 결과 창 UI 변경
- [ ] 제품 페이지 UI 변경
- [ ] 루틴 페이지 UI 변경
