### ISSUE TITLE
Backend To-do's

### ISSUE THREAD

**Issue by jaenam615** [jaenam615/cosmetic_routine#35]
- [ ] cart API
- [ ] transaction module
- [ ] item order API
- [ ] order detail API
- [ ] item & routine filtering

**Comment by CamelIsTheBestConvention** [comment]
- [] 장바구니 동일한 item_key 중복 시 수량 추가
- [] GET /api/order/itemorder 500 error 확인 요망

**Comment by jaenam615** [comment]
- [ ] 배포 

- [ ] 다른 주소 기본 배송지 설정 시 기존 기본 배송지 'N'으로 변경

**Comment by CamelIsTheBestConvention** [comment]
- [ ] 프로필 수정 비밀번호 변경
- [ ] 상세 루틴 attribute & tag 데이터 추가
